/*
 * Copyright (c) 2022, Daniel Beßler
 * All rights reserved.
 *
 * This file is part of KnowRob, please consult
 * https://github.com/knowrob/knowrob for license details.
 */

#ifndef __KNOWROB_IANSWER_LISTENER_H__
#define __KNOWROB_IANSWER_LISTENER_H__

// boost
#include <boost/shared_ptr.hpp>

#include "knowrob/lang/Answer.h"

namespace knowrob {
    /**
     * Interface for receiving answers generated by reasoning systems.
     */
    class IAnswerListener {
    public:
        virtual ~IAnswerListener() {}

        /** Receive an answer.
         *
         * @param answer the new answer
         */
        virtual void receiveAnswer(const boost::shared_ptr<Answer> &answer) = 0;
    };
}

#endif //__KNOWROB_IANSWER_LISTENER_H__
