/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_tum_cs_ias_knowrob_comp_cap_CapROSClient */

#ifndef _Included_edu_tum_cs_ias_knowrob_comp_cap_CapROSClient
#define _Included_edu_tum_cs_ias_knowrob_comp_cap_CapROSClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_tum_cs_ias_knowrob_comp_cap_CapROSClient
 * Method:    getHeader
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_edu_tum_cs_ias_knowrob_comp_1cap_CapROSClient_getHeader
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
