/*
 * Copyright (c) 2022, Daniel Beßler
 * All rights reserved.
 *
 * This file is part of KnowRob, please consult
 * https://github.com/knowrob/knowrob for license details.
 */

#ifndef __KNOWROB_IREASONER_H__
#define __KNOWROB_IREASONER_H__

#include "knowrob/lang/Predicate.h"
#include "knowrob/qa/Query.h"
#include "knowrob/qa/AnswerStream.h"

namespace knowrob {
    /**
     * Indicates the status of a reasoning process.
     */
    enum ReasoningStatus {
        REASONING_STATUS_RUNNING,
        REASONING_STATUS_FINISHED,
        // TODO: how to instruct a reasoner to stop?
        //          - could do it via AnswerStream
        REASONING_STATUS_STOPPED,
        REASONING_STATUS_INVALID_INPUT,
        REASONING_STATUS_INTERNAL_ERROR
    };

    /**
     * The interface for reasoning subsystems.
     */
    class IReasoner {
    public:
        virtual ~IReasoner() {}

        /** Find out whether this reasoner can handle a given predicate.
         *
         * Note that, following the Syntax of the querying language,
         * for a reasoner to be able to answer the `,\2` predicate entails that the
         * reasoner can handle conjunctive queries, `;\2` disjunctive queries etc.
         *
         * @param predicate the predicate in question
         * @return true if the reasoner can determine the truth of given predicate.
         */
        virtual bool canReasonAbout(const Predicate &predicate) const = 0;

        /** Run the reasoner to answer a given query.
         *
         * This function is usually called in a separate thread.
         * Hence, make sure IReasoner implementations are thread-safe.
         *
         * @param goal the query made of predicates that can be answered by the reasoner
         * @param publisher the publisher for answers generated by the reasoner if any
         * @return the status of processing the given goal
         */
        virtual ReasoningStatus answer(const Query &goal, IAnswerPublisher &publisher) = 0;
    };
}

#endif //__KNOWROB_IREASONER_H__
