#!/bin/bash

# search for files 'classpath.txt' in all packages

output=""
is_first=1
for ROS_PATH in `echo $ROS_PACKAGE_PATH | tr ":" "\n"`
do
    for CLASS_PATH_FILE in `find -L $ROS_PATH -path '*/build/classpath.txt' 2> /dev/null`; do
        if [ $is_first -eq 0 ]; then
            output="$output:"
        fi
        clp=`cat $CLASS_PATH_FILE`
        output="$output$clp"
        is_first=0
    done
done
echo $output | tr -d '\n' | tr ':' '\n' | sort -u | tr '\n' ':'
