#!/bin/bash

# search for files 'classpath.txt' in all packages the package $1 depends on
# and concatenate the classpath variables

ROS_CP=$2

# find classpath for package itself
PKG_PATH=`rospack find $1`
for cp in `find $PKG_PATH -name classpath.txt`; do
  ROS_CP=`cat ${cp}`:$ROS_CP
done

# find classpath for all dependencies
for dep in `rospack depends $1`; do
  PKG_PATH=`rospack find $dep`
  for cp in `find $PKG_PATH -name classpath.txt`; do
    ROS_CP=`cat ${cp}`:$ROS_CP
  done
done

# remove duplicates in the classpath
ROS_CP=$(echo "$ROS_CP" | awk -v RS=':' -v ORS=":" '!a[$1]++')

echo $ROS_CP

