#!/bin/bash
#
# Finds all files with the given extensions in any subdirectory of the current
# directory and replaces the IRIs with the new knowrob.org IRIs.
# 
# The default extensions are *.owl *.rdf *.pl *.cpp *.java *.json *.yaml *.l *.js *.lisp *.py
# You can add additional file types using the -e argument.
# 

OPTIND=1
extensions='owl rdf pl cpp java json yaml l js lisp py'

while getopts "he:" opt ; do
  case "$opt" in
    e) extensions=$OPTARG
      ;;
    h)
      echo "Usage: migrate_owl_iri -e '<extensions>'"
      echo "Default: migrate_owl_iri -e '$extensions'"
      exit 0
      ;;
  esac
done

# search for all file types and replace the contained IRIs 
for ext in $extensions; do
  for f in `find . -name "*.${ext}*"`
  do
    echo "Migrating $f..."
    sed "s:http\:\/\/ias\.cs\.tum\.edu\/kb:http\:\/\/knowrob\.org\/kb:g" $f > "$f.tmp"
    mv "$f.tmp" $f
  done
done

