#!/bin/bash

PL_ARGS=$@
PL_INIT_FILE=$(rospack find rosprolog)/prolog/init.pl
SCRIPT_FILE=""

if [ -n "$1" ] && [ -n "$(rospack find $1)" ]; then

    if [ -f $(rospack find $1)/prolog/init.pl ]; then
        SCRIPT_FILE="-g register_ros_package($1)"
    fi
    PL_ARGS=${@:1}
fi

if [ -n "$2" ]; then
    SCRIPT_FILE=$SCRIPT_FILE",$2"
fi

exec /usr/bin/swipl -s ${PL_INIT_FILE} ${SCRIPT_FILE} ${PL_ARGS}
