#!/bin/bash

PL_ARGS=$@
PL_INIT_FILE=$(rospack find rosprolog)/prolog/init.pl
PLDOC_INIT_FILE=$(rospack find rosprolog)/prolog/doc-init.pl
SCRIPT_FILE=""

if [ -n "$1" ] && [ -n "$(rospack find $1)" ]; then
    ROS_EXPORT_CLASSPATH=`$(rospack find rosprolog)/scripts/get_pkg_classpath $1`
    export CLASSPATH=$ROS_EXPORT_CLASSPATH:$CLASSPATH

    if [ -f $(rospack find $1)/prolog/init.pl ]; then
        SCRIPT_FILE="-g ensure_loaded('${PL_INIT_FILE}'),register_ros_package($1),doc_save('$(rospack find $1)/',[format(html),recursive(true),doc_root('$(rospack find $1)/doc')]) -t halt"
    fi
    PL_ARGS=${@:1}
fi

cd "$(rospack find $1)"
exec /usr/bin/swipl -q -f ${PLDOC_INIT_FILE}  ${SCRIPT_FILE} ${PL_ARGS}
