#!/bin/bash

if [ -z "$2" ]; then
    echo "Usage: $0 <ros package> <command> [param]*"
    exit 1
fi

source $(rospack find rosprolog)/scripts/rosprolog_utils.sh

get_pkg_classpath $1 ROS_EXPORT_CLASSPATH
get_pkg_ld_lib_path $1 ROS_EXPORT_LD
export CLASSPATH=$ROS_EXPORT_CLASSPATH:$CLASSPATH
export LD_LIBRARY_PATH=$ROS_EXPORT_LD:$LD_LIBRARY_PATH:$(rospack find rosjava_jni)/bin

exec $2 $1 ${@:2}
