include $(shell rospack find mk)/cmake.mk

all:unpack

unpack:
	# untar the germandeli.owl file (it's packed because it's so large...)
	tar xf owl/germandeli.tar.gz -C owl
	tar xf owl/germandeli-small.tar.gz -C owl
