/* auto-generated by gensrv_java from /work/ros/tumros-internal/stacks/knowrob/comp_ehow/srv/EhowToOWL.srv.  Do not edit! */
package ros.pkg.comp_ehow.srv;

import java.nio.ByteBuffer;

public class EhowToOWL extends ros.communication.Service<EhowToOWL.Request, EhowToOWL.Response> 
{

public static String __s_getDataType() { return "comp_ehow/EhowToOWL"; }
public static String __s_getMD5Sum() { return "757be2a3a997cc31d4d3125810ee07f5"; }

public String getDataType() { return EhowToOWL.__s_getDataType(); }
public String getMD5Sum() { return EhowToOWL.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public java.lang.String command;

  public Request() {
 super();
    command = new java.lang.String();

  }
  public static java.lang.String __s_getDataType() { return "comp_ehow/EhowToOWLRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "# Moritz Tenorth, tenorth@cs.tum.edu\n" + 
    "# service to retrieve a how-to for a query string and return an OWL representation\n" + 
    "string command\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("757be2a3a997cc31d4d3125810ee07f5"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("comp_ehow/EhowToOWL"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("command", "java.lang.String");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    command = __m2.command;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + command.length(); // command
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, command);
  }
  public void deserialize(ByteBuffer bb)  {
    command = Serialization.readString(bb);
  }
}

public static class Response extends ros.communication.Message
{

  public java.lang.String owl_instructions;

  public Response() {
 super();
    owl_instructions = new java.lang.String();

  }
  public static java.lang.String __s_getDataType() { return "comp_ehow/EhowToOWLResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string owl_instructions\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("757be2a3a997cc31d4d3125810ee07f5"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("comp_ehow/EhowToOWL"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("owl_instructions", "java.lang.String");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    owl_instructions = __m2.owl_instructions;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + owl_instructions.length(); // owl_instructions
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, owl_instructions);
  }
  public void deserialize(ByteBuffer bb)  {
    owl_instructions = Serialization.readString(bb);
  }
}

public EhowToOWL.Request createRequest() { return new EhowToOWL.Request(); }public EhowToOWL.Response createResponse() { return new EhowToOWL.Response(); }}

